### ISSUE TITLE
Quorum helm chart - value of  quorum_node_no:

### ISSUE THREAD

**Issue by boldis** [PharmaLedger-IMI/helm-charts#84]
I think that value of  quorum_node_no: should be specified as string, otherwise template will not render it correctly:
Problem I think lies here: 
File:  _helm-charts\charts\quorum-node\templates\_helpers.tpl_
Line 57:` {{- printf "%s-%s" $name .Values.deployment.quorum_node_no | trunc 63 }}` 

 if specified as integer will render from:
  `quorum_node_no: 1`
into: 
 ` %!s(float64=1)`

Proposal to fix: change description in the values.yaml:
 `# -- The number of the deployed Quorum node - specify as a string
`

**Comment by boldis** [comment]
One more thing - there are missing section in values.yaml  for storageClass.enabled since it is referenced in the template. I would have created a pull request but I have no priviledge in this repo. So I place it here - updated from line 169:
<pre>
  peers: []

# enable storageclass creation
storageClass:
  enabled: true

# Persistence using Persistent Volume Claims
# See [http://kubernetes.io/docs/user-guide/persistent-volumes/](http://kubernetes.io/docs/user-guide/persistent-volumes/)
persistence:
 </pre>

**Comment by tgip-work** [comment]
Hello @boldis : The first issue is fixed. See Fixed in quorum-node-0.4.0 - see [https://github.com/PharmaLedger-IMI/helm-charts/tree/quorum-node-0.4.0/charts/quorum-node](https://github.com/PharmaLedger-IMI/helm-charts/tree/quorum-node-0.4.0/charts/quorum-node) and [https://github.com/PharmaLedger-IMI/helm-charts/pull/115](https://github.com/PharmaLedger-IMI/helm-charts/pull/115)

Your second issue regarding the storageClass: I cannot find this anywhere. If it still exists can you open a new issue for that, please
